[package]
name = "vir_py-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
vir_py_rs_type = { path = "vir_py_rs_type"}
vir_py_rs_parser = { path = "vir_py_rs_macro"}

[workspace]
members = [
    "vir_py_rs_type",
    "vir_py_rs_macro",
    "vir_py_rs_parser"
]